config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :lead_dates

end

app/models/lead_date.rb
class LeadDate < ActiveRecord::Base
  validates :lead_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lead_dates_controller.rb
class LeadDatesController < ApplicationController
  require 'csv'

  def index
    @lead_dates = LeadDate.all
  end

  def create
    lead_id = params[:lead_id]

    if lead_id.blank?
      flash[:notice] = "lead id can't be blank!"
      return redirect_to root_path
    end

    if LeadDate.exists?(lead_id: lead_id)
      flash[:notice] = "lead id already exists!"
      return redirect_to root_path
    end
    first_date, second_date, third_date = generate_random_date
    LeadDate.create!(
      lead_id: lead_id,
      first_date: first_date,
      second_date: second_date,
      third_date: third_date
    )
    flash[:notice] = "Created random dates for #{lead_id}!"
    return redirect_to root_path
  end

  private

  def generate_random_date
    dates = []
    while dates.length < 3 do
      temp_date = rand(4.months).seconds.ago
      puts temp_date
      months_array = dates.map{|dt| dt.month}
      temp_date_not_in_list = !months_array.include?(temp_date.month)
      temp_date_not_current_month = !(temp_date.month == Time.now.month)
      puts temp_date_not_in_list && temp_date_not_current_month
      dates.push(temp_date) if temp_date_not_in_list && temp_date_not_current_month
    end
    dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lead_dates_helper.rb
module LeadDatesHelper
end

app/views/home/index.html.haml
.container.text-center.mt100
  .row
    .col-xs-12
      %h1 Enter lead id
  .row
    .col-xs-12.pl20p.pr20p
      = form_tag(controller: :lead_dates, action: :create) do
        = text_field_tag :lead_id, '', class: 'form-control mb10'
        = button_tag 'Generate random dates', type: :submit, class: 'btn btn-block btn-default'

.container.mt10.text-center
  .row
    .col-xs-12
      %a{href:"#{lead_dates_path}"}
        Go To Dashboard

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FcRandomizer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}/
  %body
    .container.text-center
      - if flash[:notice]
        .row
          .col-xs-12.pl20p.pr20p
            .notice.alert.alert-warning= flash[:notice]
    = yield

app/views/lead_dates/index.html.haml
.container
  .row
    .col-xs-12
      %h1 Leads with 3 Dates
  .row
    .col-xs-12
      %table.table.table-condensed
        %tr
          %th
            Lead ID
          %th
            First Date
          %th
            Second Date
          %th
            Third Date
        - @lead_dates.each do |lead_date|
          %tr
            %th= lead_date.lead_id
            %th= lead_date.first_date
            %th= lead_date.second_date
            %th= lead_date.third_date